management:
  endpoints:
    web:
      exposure:
        include: httptrace,health
logging:
  level:
   org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
   pl.tomlewlit.kafkacompanion: DEBUG
